# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bafd1e5336dfcdee64c0a9e018ecab4831952202c86b315305acbb936de0fbe799f364208d9d805a513443e5e8352839241c2bdcb39b8456497f01656ce65fcc

test:
  secret_key_base: 56c3617b3235e21450e470363d0af3de4a313957d6a0bc264240fef7e70e2c4c3ab79e891544eabfc774fd8ba0255fe303e33207f5e0cc6563afdb2ddd363ce4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
